[custom]
ruleset=ğŸ—‚ï¸ OneDrive,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/OneDrive.list
ruleset=ğŸ’» Microsoft,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Microsoft.list
ruleset=ğŸ Apple,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Apple.list
ruleset=ğŸ“² Telegram,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Telegram.list
ruleset=ğŸ“² Discord,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/Discord.list
ruleset=ğŸ“² Line,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/Line.list
ruleset=ğŸ“² Line TV,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/LineTV.list
ruleset=ğŸª™ Crypto,https://cdn.jsdelivr.net/gh/bk1d/oc_config@main/Crypto.list
ruleset=ğŸ¤– OpenAI,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/OpenAi.list
ruleset=ğŸ¤– Claude,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/Claude.list
ruleset=ğŸ¤– Gemini,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/Gemini.list
ruleset=ğŸ’° Paypal,https://cdn.jsdelivr.net/gh/bk1d/oc_config@main/PayPal.list
ruleset=ğŸ›’ Amazon,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/Amazon.list
ruleset=ğŸŒ Google,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/Google.list
ruleset=ğŸŒ Reddit,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/Reddit.list
ruleset=ğŸ“¹ Porn,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/Porn.list
ruleset=ğŸ“¹ Pikpak,https://cdn.jsdelivr.net/gh/bk1d/oc_config@main/Pikpak.yaml
ruleset=ğŸ“¹ Tiktok,https://cdn.jsdelivr.net/gh/bk1d/oc_config@main/tiktok.list
ruleset=ğŸ“¹ DAZN,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/DAZN.list
ruleset=ğŸ“¹ HBO,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/HBO.list
ruleset=ğŸ“¹ Hulu,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/Hulu.list
ruleset=ğŸ“¹ DisneyPlus,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/DisneyPlus.list
ruleset=ğŸ“¹ Twitch,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/Twitch.list
ruleset=ğŸ¥ Netflix,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/Netflix.list
ruleset=ğŸ¥ Deezer,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/Deezer.list
ruleset=ğŸ§© Github,https://cdn.jsdelivr.net/gh/bk1d/oc_config@main/github.list
ruleset=ğŸ§© JetBrains,https://cdn.jsdelivr.net/gh/bk1d/oc_config@main/JetBrains.list
ruleset=ğŸ¦œ Twitter,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/Twitter.list
ruleset=ğŸ® Steam,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/Steam.list
ruleset=ğŸ® SteamCN,https://cdn.jsdelivr.net/gh/bk1d/oc_config@main/SteamCN.list
ruleset=ğŸ® Xbox,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Xbox.list
ruleset=ğŸ¤¡ CustomAsshole,https://cdn.jsdelivr.net/gh/bk1d/oc_config@main/CustomAsshole.list
ruleset=ğŸ¤¡ CNService,https://cdn.jsdelivr.net/gh/bk1d/oc_config@main/oray.list
ruleset=ğŸ¤¡ TWService,https://cdn.jsdelivr.net/gh/bk1d/oc_config@main/tw.list
ruleset=Domestic,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/LocalAreaNetwork.list
ruleset=Domestic,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/UnBan.list
ruleset=Domestic,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/GoogleCN.list
ruleset=Domestic,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/ChinaIp.list
ruleset=Domestic,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/ChinaDomain.list
ruleset=Domestic,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/ChinaCompanyIp.list
ruleset=Domestic,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Download.list
ruleset=Domestic,[]GEOIP,CN
ruleset=Others,[]FINAL
custom_proxy_group=ğŸš€ Auto`select`[]HK`[]MO`[]JP`[]USA`[]SG`[]TW`[]KR`[]â™»ï¸ AutoAll`[]ğŸ§œâ€â™‚ï¸ æ‰‹åŠ¨é€‰æ‹©`[]DIRECT
custom_proxy_group=ğŸ§œâ€â™‚ï¸ æ‰‹åŠ¨é€‰æ‹©`select`.*
custom_proxy_group=â™»ï¸ AutoAll`url-test`.*`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=Domestic`select`[]DIRECT`[]ğŸš€ Auto`[]â™»ï¸ AutoAll`[]ğŸ§œâ€â™‚ï¸ æ‰‹åŠ¨é€‰æ‹©
custom_proxy_group=ğŸ—‚ï¸ OneDrive`select`[]ğŸš€ Auto`[]HK`[]MO`[]JP`[]USA`[]SG`[]TW`[]KR`[]â™»ï¸ AutoAll`[]ğŸ§œâ€â™‚ï¸ æ‰‹åŠ¨é€‰æ‹©`[]DIRECT
custom_proxy_group=ğŸ’» Microsoft`select`[]DIRECT`[]ğŸš€ Auto`[]HK`[]MO`[]JP`[]USA`[]SG`[]TW`[]KR`[]â™»ï¸ AutoAll`[]ğŸ§œâ€â™‚ï¸ æ‰‹åŠ¨é€‰æ‹©
custom_proxy_group=ğŸ Apple`select`[]DIRECT`[]ğŸš€ Auto`[]HK`[]MO`[]JP`[]USA`[]SG`[]TW`[]KR`[]â™»ï¸ AutoAll`[]ğŸ§œâ€â™‚ï¸ æ‰‹åŠ¨é€‰æ‹©
custom_proxy_group=ğŸ“² Telegram`select`[]ğŸš€ Auto`[]HK`[]MO`[]JP`[]USA`[]SG`[]TW`[]KR`[]â™»ï¸ AutoAll`[]ğŸ§œâ€â™‚ï¸ æ‰‹åŠ¨é€‰æ‹©`[]DIRECT
custom_proxy_group=ğŸ“² Discord`select`[]ğŸš€ Auto`[]HK`[]MO`[]JP`[]USA`[]SG`[]TW`[]KR`[]â™»ï¸ AutoAll`[]ğŸ§œâ€â™‚ï¸ æ‰‹åŠ¨é€‰æ‹©`[]DIRECT
custom_proxy_group=ğŸ“² Line`select`[]ğŸš€ Auto`[]HK`[]MO`[]JP`[]USA`[]SG`[]TW`[]KR`[]â™»ï¸ AutoAll`[]ğŸ§œâ€â™‚ï¸ æ‰‹åŠ¨é€‰æ‹©`[]DIRECT
custom_proxy_group=ğŸ“² Line TV`select`[]ğŸš€ Auto`[]HK`[]MO`[]JP`[]USA`[]SG`[]TW`[]KR`[]â™»ï¸ AutoAll`[]ğŸ§œâ€â™‚ï¸ æ‰‹åŠ¨é€‰æ‹©`[]DIRECT
custom_proxy_group=ğŸª™ Crypto`select`[]JP`[]ğŸš€ Auto`[]HK`[]MO`[]USA`[]SG`[]TW`[]KR`[]â™»ï¸ AutoAll`[]ğŸ§œâ€â™‚ï¸ æ‰‹åŠ¨é€‰æ‹©`[]DIRECT
custom_proxy_group=ğŸ¤– OpenAI`select`[]JP`[]ğŸš€ Auto`[]HK`[]MO`[]USA`[]SG`[]TW`[]KR`[]â™»ï¸ AutoAll`[]ğŸ§œâ€â™‚ï¸ æ‰‹åŠ¨é€‰æ‹©`[]DIRECT
custom_proxy_group=ğŸ¤– Claude`select`[]JP`[]ğŸš€ Auto`[]HK`[]MO`[]USA`[]SG`[]TW`[]KR`[]â™»ï¸ AutoAll`[]ğŸ§œâ€â™‚ï¸ æ‰‹åŠ¨é€‰æ‹©`[]DIRECT
custom_proxy_group=ğŸ¤– Gemini`select`[]JP`[]ğŸš€ Auto`[]HK`[]MO`[]USA`[]SG`[]TW`[]KR`[]â™»ï¸ AutoAll`[]ğŸ§œâ€â™‚ï¸ æ‰‹åŠ¨é€‰æ‹©`[]DIRECT
custom_proxy_group=ğŸ“¹ Tiktok`select`[]JP`[]ğŸš€ Auto`[]HK`[]MO`[]USA`[]SG`[]TW`[]KR`[]â™»ï¸ AutoAll`[]ğŸ§œâ€â™‚ï¸ æ‰‹åŠ¨é€‰æ‹©`[]DIRECT
custom_proxy_group=ğŸ’° Paypal`select`[]USA`[]ğŸš€ Auto`[]HK`[]MO`[]JP`[]SG`[]TW`[]KR`[]â™»ï¸ AutoAll`[]ğŸ§œâ€â™‚ï¸ æ‰‹åŠ¨é€‰æ‹©`[]DIRECT
custom_proxy_group=ğŸ›’ Amazon`select`[]USA`[]ğŸš€ Auto`[]HK`[]MO`[]JP`[]SG`[]TW`[]KR`[]â™»ï¸ AutoAll`[]ğŸ§œâ€â™‚ï¸ æ‰‹åŠ¨é€‰æ‹©`[]DIRECT
custom_proxy_group=ğŸ“¹ DAZN`select`[]USA`[]ğŸš€ Auto`[]HK`[]MO`[]JP`[]SG`[]TW`[]KR`[]â™»ï¸ AutoAll`[]ğŸ§œâ€â™‚ï¸ æ‰‹åŠ¨é€‰æ‹©`[]DIRECT
custom_proxy_group=ğŸ“¹ HBO`select`[]USA`[]ğŸš€ Auto`[]HK`[]MO`[]JP`[]SG`[]TW`[]KR`[]â™»ï¸ AutoAll`[]ğŸ§œâ€â™‚ï¸ æ‰‹åŠ¨é€‰æ‹©`[]DIRECT
custom_proxy_group=ğŸ“¹ Hulu`select`[]USA`[]ğŸš€ Auto`[]HK`[]MO`[]JP`[]SG`[]TW`[]KR`[]â™»ï¸ AutoAll`[]ğŸ§œâ€â™‚ï¸ æ‰‹åŠ¨é€‰æ‹©`[]DIRECT
custom_proxy_group=ğŸ“¹ DisneyPlus`select`[]USA`[]ğŸš€ Auto`[]HK`[]MO`[]JP`[]SG`[]TW`[]KR`[]â™»ï¸ AutoAll`[]ğŸ§œâ€â™‚ï¸ æ‰‹åŠ¨é€‰æ‹©`[]DIRECT
custom_proxy_group=ğŸŒ Google`select`[]ğŸš€ Auto`[]HK`[]MO`[]JP`[]USA`[]SG`[]TW`[]KR`[]â™»ï¸ AutoAll`[]ğŸ§œâ€â™‚ï¸ æ‰‹åŠ¨é€‰æ‹©`[]DIRECT
custom_proxy_group=ğŸŒ Reddit`select`[]ğŸš€ Auto`[]HK`[]MO`[]JP`[]USA`[]SG`[]TW`[]KR`[]â™»ï¸ AutoAll`[]ğŸ§œâ€â™‚ï¸ æ‰‹åŠ¨é€‰æ‹©`[]DIRECT
custom_proxy_group=ğŸ“¹ Porn`select`[]ğŸš€ Auto`[]HK`[]MO`[]JP`[]USA`[]SG`[]TW`[]KR`[]â™»ï¸ AutoAll`[]ğŸ§œâ€â™‚ï¸ æ‰‹åŠ¨é€‰æ‹©`[]DIRECT
custom_proxy_group=ğŸ“¹ Pikpak`select`[]ğŸš€ Auto`[]HK`[]MO`[]JP`[]USA`[]SG`[]TW`[]KR`[]â™»ï¸ AutoAll`[]ğŸ§œâ€â™‚ï¸ æ‰‹åŠ¨é€‰æ‹©`[]DIRECT
custom_proxy_group=ğŸ“¹ Twitch`select`[]ğŸš€ Auto`[]HK`[]MO`[]JP`[]USA`[]SG`[]TW`[]KR`[]â™»ï¸ AutoAll`[]ğŸ§œâ€â™‚ï¸ æ‰‹åŠ¨é€‰æ‹©`[]DIRECT
custom_proxy_group=ğŸ¥ Netflix`select`[]ğŸš€ Auto`[]HK`[]MO`[]JP`[]USA`[]SG`[]TW`[]KR`[]â™»ï¸ AutoAll`[]ğŸ§œâ€â™‚ï¸ æ‰‹åŠ¨é€‰æ‹©`[]DIRECT
custom_proxy_group=ğŸ¥ Deezer`select`[]ğŸš€ Auto`[]SG`[]HK`[]MO`[]JP`[]USA`[]TW`[]KR`[]â™»ï¸ AutoAll`[]ğŸ§œâ€â™‚ï¸ æ‰‹åŠ¨é€‰æ‹©`[]DIRECT
custom_proxy_group=ğŸ§© Github`select`[]ğŸš€ Auto`[]HK`[]MO`[]JP`[]USA`[]SG`[]TW`[]KR`[]â™»ï¸ AutoAll`[]ğŸ§œâ€â™‚ï¸ æ‰‹åŠ¨é€‰æ‹©`[]DIRECT
custom_proxy_group=ğŸ§© JetBrains`select`[]TW`[]ğŸš€ Auto`[]HK`[]MO`[]JP`[]USA`[]SG`[]KR`[]â™»ï¸ AutoAll`[]ğŸ§œâ€â™‚ï¸ æ‰‹åŠ¨é€‰æ‹©`[]DIRECT
custom_proxy_group=ğŸ¦œ Twitter`select`[]ğŸš€ Auto`[]HK`[]MO`[]JP`[]USA`[]SG`[]TW`[]KR`[]â™»ï¸ AutoAll`[]ğŸ§œâ€â™‚ï¸ æ‰‹åŠ¨é€‰æ‹©`[]DIRECT
custom_proxy_group=ğŸ® Steam`select`[]ğŸš€ Auto`[]HK`[]MO`[]JP`[]USA`[]SG`[]TW`[]KR`[]â™»ï¸ AutoAll`[]ğŸ§œâ€â™‚ï¸ æ‰‹åŠ¨é€‰æ‹©`[]DIRECT
custom_proxy_group=ğŸ® SteamCN`select`[]DIRECT`[]ğŸš€ Auto`[]HK`[]MO`[]JP`[]USA`[]SG`[]TW`[]KR`[]â™»ï¸ AutoAll`[]ğŸ§œâ€â™‚ï¸ æ‰‹åŠ¨é€‰æ‹©
custom_proxy_group=ğŸ® Xbox`select`[]ğŸš€ Auto`[]HK`[]MO`[]JP`[]USA`[]SG`[]TW`[]KR`[]â™»ï¸ AutoAll`[]ğŸ§œâ€â™‚ï¸ æ‰‹åŠ¨é€‰æ‹©`[]DIRECT
custom_proxy_group=ğŸ¤¡ CustomAsshole`select`[]JP`[]ğŸš€ Auto`[]HK`[]MO`[]USA`[]SG`[]TW`[]KR`[]â™»ï¸ AutoAll`[]ğŸ§œâ€â™‚ï¸ æ‰‹åŠ¨é€‰æ‹©`[]DIRECT
custom_proxy_group=ğŸ¤¡ CNService`select`[]DIRECT`[]ğŸš€ Auto`[]HK`[]MO`[]JP`[]USA`[]SG`[]TW`[]KR`[]â™»ï¸ AutoAll`[]ğŸ§œâ€â™‚ï¸ æ‰‹åŠ¨é€‰æ‹©
custom_proxy_group=ğŸ¤¡ TWService`select`[]TW`[]ğŸš€ Auto`[]HK`[]MO`[]JP`[]USA`[]SG`[]KR`[]â™»ï¸ AutoAll`[]ğŸ§œâ€â™‚ï¸ æ‰‹åŠ¨é€‰æ‹©`[]DIRECT
custom_proxy_group=Others`select`[]ğŸš€ Auto`[]HK`[]MO`[]JP`[]USA`[]SG`[]TW`[]KR`[]â™»ï¸ AutoAll`[]ğŸ§œâ€â™‚ï¸ æ‰‹åŠ¨é€‰æ‹©`[]DIRECT
custom_proxy_group=HK`url-test`(é¦™æ¸¯)`http://www.gstatic.com/generate_204`300,5,50
custom_proxy_group=MO`url-test`(æ¾³é—¨)`http://www.gstatic.com/generate_204`300,5,50
custom_proxy_group=JP`url-test`(æ—¥æœ¬)`http://www.gstatic.com/generate_204`300,5,50
custom_proxy_group=USA`url-test`(ç¾å›½)`http://www.gstatic.com/generate_204`300,5,50
custom_proxy_group=SG`url-test`(æ–°åŠ å¡)`http://www.gstatic.com/generate_204`300,5,50
custom_proxy_group=TW`url-test`(å°æ¹¾)`http://www.gstatic.com/generate_204`300,5,50
custom_proxy_group=KR`url-test`(éŸ©å›½)`http://www.gstatic.com/generate_204`300,5,50
clash_rule_base=https://raw.githubusercontent.com/bk1d/oc_config/refs/heads/main/clash_rule_base_v4.yml
enable_rule_generator=true
overwrite_original_rules=true
